import os
from pathlib import Path

import psycopg2
from psycopg2 import sql


BASE_DIR = Path(__file__).resolve().parents[1]
DEFAULT_TABLE = "public.移仓换月宽表"


def parse_table_name(table_name: str):
    parts = table_name.split(".")
    if len(parts) == 1:
        schema_name = "public"
        relation_name = parts[0]
    elif len(parts) == 2:
        schema_name, relation_name = parts
    else:
        raise ValueError("PG_TABLE 只支持 table 或 schema.table 格式")

    for value in (schema_name, relation_name):
        if not value or "\x00" in value:
            raise ValueError(f"非法表名片段: {value}")
    return schema_name, relation_name


def column_exists(cur, schema_name: str, relation_name: str, column_name: str) -> bool:
    cur.execute(
        """
        select exists (
            select 1
            from information_schema.columns
            where table_schema = %s
              and table_name = %s
              and column_name = %s
        )
        """,
        (schema_name, relation_name, column_name),
    )
    return cur.fetchone()[0]


def primary_key_exists(cur, schema_name: str, relation_name: str) -> bool:
    cur.execute(
        """
        select exists (
            select 1
            from information_schema.table_constraints
            where table_schema = %s
              and table_name = %s
              and constraint_type = 'PRIMARY KEY'
        )
        """,
        (schema_name, relation_name),
    )
    return cur.fetchone()[0]


def identity_exists(cur, schema_name: str, relation_name: str) -> bool:
    cur.execute(
        """
        select is_identity = 'YES'
        from information_schema.columns
        where table_schema = %s
          and table_name = %s
          and column_name = 'id'
        """,
        (schema_name, relation_name),
    )
    row = cur.fetchone()
    return bool(row and row[0])


def add_id_column(cur, table_ident, schema_name: str, relation_name: str) -> None:
    if not column_exists(cur, schema_name, relation_name, "id"):
        cur.execute(sql.SQL("ALTER TABLE {} ADD COLUMN id BIGINT").format(table_ident))

    cur.execute(
        sql.SQL(
            """
            WITH numbered AS (
                SELECT ctid, coalesce((SELECT max(id) FROM {}), 0) + row_number() OVER () AS new_id
                FROM {}
                WHERE id IS NULL
            )
            UPDATE {}
            SET id = numbered.new_id
            FROM numbered
            WHERE {}.ctid = numbered.ctid
            """
        ).format(table_ident, table_ident, table_ident, table_ident)
    )
    cur.execute(sql.SQL("ALTER TABLE {} ALTER COLUMN id SET NOT NULL").format(table_ident))

    if not identity_exists(cur, schema_name, relation_name):
        cur.execute(sql.SQL("ALTER TABLE {} ALTER COLUMN id DROP DEFAULT").format(table_ident))
        cur.execute(
            sql.SQL("ALTER TABLE {} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY").format(
                table_ident
            )
        )
        cur.execute(sql.SQL("SELECT coalesce(max(id), 0) + 1 FROM {}").format(table_ident))
        next_id = cur.fetchone()[0]
        cur.execute(
            sql.SQL("ALTER TABLE {} ALTER COLUMN id RESTART WITH {}").format(
                table_ident,
                sql.Literal(next_id),
            )
        )

    if not primary_key_exists(cur, schema_name, relation_name):
        constraint_name = f"{relation_name}_pkey"
        cur.execute(
            sql.SQL("ALTER TABLE {} ADD CONSTRAINT {} PRIMARY KEY (id)").format(
                table_ident,
                sql.Identifier(constraint_name),
            )
        )


def add_timestamp_columns(cur, table_ident) -> None:
    cur.execute(
        sql.SQL(
            "ALTER TABLE {} ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now()"
        ).format(table_ident)
    )
    cur.execute(
        sql.SQL(
            "ALTER TABLE {} ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now()"
        ).format(table_ident)
    )


def add_updated_at_trigger(cur, table_ident, schema_name: str, relation_name: str) -> None:
    function_name = f"set_{relation_name}_updated_at"
    trigger_name = f"trg_{relation_name}_updated_at"

    cur.execute(
        sql.SQL(
            """
            CREATE OR REPLACE FUNCTION {}.{}()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.updated_at = now();
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
            """
        ).format(sql.Identifier(schema_name), sql.Identifier(function_name))
    )
    cur.execute(sql.SQL("DROP TRIGGER IF EXISTS {} ON {}").format(sql.Identifier(trigger_name), table_ident))
    cur.execute(
        sql.SQL(
            """
            CREATE TRIGGER {}
            BEFORE UPDATE ON {}
            FOR EACH ROW
            EXECUTE FUNCTION {}.{}()
            """
        ).format(
            sql.Identifier(trigger_name),
            table_ident,
            sql.Identifier(schema_name),
            sql.Identifier(function_name),
        )
    )


def main() -> int:
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        print("missing_DATABASE_URL = true")
        print("请先在 PowerShell 设置 $env:DATABASE_URL")
        return 1

    table_name = os.environ.get("PG_TABLE", DEFAULT_TABLE)
    schema_name, relation_name = parse_table_name(table_name)
    table_ident = sql.SQL("{}.{}").format(sql.Identifier(schema_name), sql.Identifier(relation_name))

    with psycopg2.connect(database_url) as conn:
        with conn.cursor() as cur:
            add_id_column(cur, table_ident, schema_name, relation_name)
            add_timestamp_columns(cur, table_ident)
            add_updated_at_trigger(cur, table_ident, schema_name, relation_name)

    print(f"table = {schema_name}.{relation_name}")
    print("id_auto_increment = true")
    print("created_at_auto_record = true")
    print("updated_at_auto_refresh = true")
    print("schema_update_finished = true")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
